### ISSUE TITLE
Inverted display

### ISSUE THREAD

**Issue by spycat88** [anpaza/linux_vfd#1]
I have a device which appears to have an inverted display (Tanix TX3 Mini), I have managed to use your vfd driver to get it working but everything is upside down.

Is it possible for you to add an option to configure a device with an inverted display via the device tree source.

**Comment by anpaza** [comment]
Hello Adam, I somehow overlooked your message but someone brought to my attention your post on libreelec:
https://forum.libreelec.tv/thread/10301-8-90-4-libreelec-9-0-alpha-for-s905-s912-devices/?postID=78148#post78148

It is possible to invert the glyphs, for this you have to change the array vfd_glyphs in vfd-glyphs.c.
It should be fairly easy to do.If you manage to do it, I would be glad to receive the modified vfd-glyphs so that I can integrate it into the mainline and add a choice to kernel menuconfig.

Also I can try to help you, although without the hardware that would take longer because of the ping-pong. It would help if you would send a photo of your "upside-down" display.
